export const ADMIN_ROUTE = '/admin'
export const CATALOG_ROUTE = '/catalog'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const BASE_ROUTE = '/'
export const BASKET_ROUTE = '/basket'
export const FAVOR_ROUTE = '/favor'
export const DELIVERY_ROUTE = '/delivery'
export const CONTACTS_ROUTE = '/contacts'
export const PRODUCT_ROUTE = '/product'
export const PERSONAL_ACCOUNT_ROUTE = '/personal_account'
export const PERSONAL_ACCOUNT_REG_ROUTE = '/personal_account_reg'
export const GUEST_ROUTE ='/guest'
export const ABOUT_ROUTE ='/about'
export const ADMIN_ACCOUNT_ROUTE = "/admin_account"
export const ADMIN_ACCOUNT_REG_ROUTE = "/admin_account_reg"
export const ADMIN_CATALOG_ROUTE = "/admin_catalog"
export const ADMIN_DELIVERIES_ROUTE = "/admin_deliveries"
export const ADMIN_GUESTS_PANEL_ROUTE = "/admin_guests_panel"
export const ORDER_ROUTE ="/order"